import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import logo from '../assets/btclin.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>btclin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>

      <div id="head">
 

        <h1>BtClin</h1>
        <img src={logo} />


      </div>
      <h2>Cadastro de consultas</h2>
      <hr></hr>
      <p>Preencha os campos a seguir.</p>
      <forms>
        <label>
          <span>Nome:</span>
          <input type="text" placeholder='digite seu nome'/>
        </label>
        <label>
<span>Número da carteira:</span>
        <input type="number"  max="14" placeholder='digite seu número da carteira'/>
</label>
<label>
<span>Cpf:</span>
        <input type="number" max="11" placeholder='digite seu cpf'/>
</label>
       
        <label id="option">
          <span>Especialidade médica:</span>
          <select >
          <option label="Cardiologista">Volvo (Latin for "I roll")</option>
          <option label="Pediatra">Saab (Swedish Aeroplane AB)</option>
          <option label="Genicologista">Mercedes (Mercedes-Benz)</option>
          <option label="Ortopedista">Audi (Auto Union Deutschland Ingolstadt)</option>
        </select>

        </label>
      <label>
        <span>
          Data:
        </span>
        <input type="date" />
      </label>
      <label>
        <span>
          Horario:
        </span>
        <select  >
          <option label="09:00 (manhã)"></option>
          <option label="14:00 (tarde)"></option>
          <option label="18:00 (noite)"></option>
        
        </select>
      </label>

       <button type="submit">Marcar</button>



      </forms>



    </>




  )
}
